const STAGES={trigger:{title:"Build the Trigger",text:"Connect the launch, workload change, and queue outcome.",combo:["push","volume","backlog"],insight:"Push introduced a high-volume event stream and queue input rose roughly 9×.",deck:[["push","volume","db","backlog","errors","volume","push","backlog","cpu","network"],["volume","push","backlog","errors","db","push","volume","backlog"]]},bottleneck:{title:"Build the Bottleneck",text:"Explain why five healthy consumers still cannot absorb the load.",combo:["consumers","idle","fifo"],insight:"Five consumers exist, but FIFO delivery prevents real parallel processing.",deck:[["consumers","idle","cpu","fifo","visibility","consumers","idle","fifo","db","errors"],["fifo","consumers","idle","network","cpu","fifo","idle","consumers"]]},mechanism:{title:"Build the Mechanism",text:"Find the exact FIFO grouping behavior that serializes work.",combo:["fifo","oneGroup","global"],insight:'All activity messages use one FIFO MessageGroupId: "global".',deck:[["fifo","oneGroup","retries","global","ordering","fifo","oneGroup","global","visibility"],["oneGroup","fifo","global","errors","ordering","fifo","global","oneGroup"]]}};
const CLUES={push:{icon:"📱",label:"Push launch",detail:"Push notifications launched immediately before lag began.",kind:"good"},volume:{icon:"🌊",label:"Traffic up 9×",detail:"Incoming activity events increased about nine-fold.",kind:"good"},backlog:{icon:"📚",label:"Backlog rising",detail:"Queue age and backlog keep growing while push is active.",kind:"good"},db:{icon:"🗄️",label:"DB normal",detail:"Database latency and write IOPS remain near baseline.",kind:"decoy"},errors:{icon:"🧯",label:"Errors low",detail:"Consumer errors and DLQ volume remain very low.",kind:"decoy"},cpu:{icon:"🧠",label:"CPU normal",detail:"Worker CPU is not saturated.",kind:"decoy"},network:{icon:"📡",label:"Network normal",detail:"Network latency remains normal.",kind:"decoy"},consumers:{icon:"⚙️",label:"5 consumers",detail:"Five consumers are configured and healthy.",kind:"good"},idle:{icon:"💤",label:"Mostly idle",detail:"Most consumers spend much of their time idle.",kind:"good"},fifo:{icon:"🚦",label:"FIFO queue",detail:"The activity pipeline uses FIFO ordering.",kind:"good"},visibility:{icon:"⏳",label:"Visibility OK",detail:"Visibility timeout exceeds average processing time.",kind:"decoy"},oneGroup:{icon:"1️⃣",label:"One group",detail:"Only one MessageGroupId is active.",kind:"good"},global:{icon:"🌐",label:'Group = "global"',detail:'Every activity message uses MessageGroupId = "global".',kind:"good"},retries:{icon:"🔁",label:"Retries low",detail:"Retry volume cannot explain the lag.",kind:"decoy"},ordering:{icon:"🔢",label:"Perfect order",detail:"Messages remain perfectly ordered despite the delay.",kind:"decoy"}};
const stageOrder=["trigger","bottleneck","mechanism"];
let state={running:false,paused:false,stageIndex:0,time:75,score:0,combo:1,lag:35,lane:1,current:null,fallY:6,fallDuration:4200,fallStarted:0,stacks:[[],[],[]],clutter:[0,0,0],insights:new Set(),powers:{freeze:1,flush:2,inspect:2},deck:[],deckIndex:0,selectedRush:{trigger:null,bottleneck:null,mechanism:null},animationId:null,timerId:null,freezeUntil:0};
const fallZone=document.getElementById("fallZone"),timeEl=document.getElementById("time"),scoreEl=document.getElementById("score"),comboEl=document.getElementById("combo"),lagFill=document.getElementById("lagFill"),lagLabel=document.getElementById("lagLabel"),toast=document.getElementById("toast");
function currentStage(){return stageOrder[state.stageIndex]}function currentConfig(){return STAGES[currentStage()]}
function resetGame(){state={running:false,paused:false,stageIndex:0,time:75,score:0,combo:1,lag:35,lane:1,current:null,fallY:6,fallDuration:4200,fallStarted:0,stacks:[[],[],[]],clutter:[0,0,0],insights:new Set(),powers:{freeze:1,flush:2,inspect:2},deck:[],deckIndex:0,selectedRush:{trigger:null,bottleneck:null,mechanism:null},animationId:null,timerId:null,freezeUntil:0};document.querySelectorAll(".stack-card,.clutter,.falling-card").forEach(e=>e.remove());document.querySelectorAll(".choice").forEach(c=>c.classList.remove("selected"));document.getElementById("finalText").value="";buildDeck();updateUI()}
function buildDeck(){state.deck=currentConfig().deck.flat();state.deckIndex=0}function nextClueId(){if(state.deckIndex>=state.deck.length)buildDeck();return state.deck[state.deckIndex++]}
function spawnClue(){if(!state.running||state.paused||state.current)return;const id=nextClueId(),clue=CLUES[id],el=document.createElement("div");el.className="falling-card"+(clue.kind==="decoy"?" decoy":"");el.innerHTML=`<span><span class="ico">${clue.icon}</span>${clue.label}</span><div class="drop-meter"><i></i></div>`;fallZone.appendChild(el);state.current={id,el};state.lane=1;state.fallY=6;state.fallStarted=performance.now();positionCurrent()}
function positionCurrent(){if(!state.current)return;const zoneW=fallZone.clientWidth,cardW=zoneW/3-12,left=state.lane*(zoneW/3)+6;state.current.el.style.width=cardW+"px";state.current.el.style.left=left+"px";state.current.el.style.top=state.fallY+"px"}
function stackHeight(l){return state.stacks[l].length+state.clutter[l]}function landingY(l){return fallZone.clientHeight-72-12-stackHeight(l)*80}
function gameLoop(now){if(!state.running)return;if(state.paused||now<state.freezeUntil){state.animationId=requestAnimationFrame(gameLoop);return}if(!state.current)spawnClue();else{const speed=(fallZone.clientHeight-92)/state.fallDuration;state.fallY+=speed*16.7;const land=landingY(state.lane),progress=Math.max(0,Math.min(1,(land-state.fallY)/(land-6||1))),meter=state.current.el.querySelector(".drop-meter i");meter.style.transform=`scaleX(${progress})`;state.fallY>=land?landCurrent():positionCurrent()}state.animationId=requestAnimationFrame(gameLoop)}
function landCurrent(){if(!state.current)return;const{id,el}=state.current,lane=state.lane;if(stackHeight(lane)>=4){el.remove();state.current=null;changeLag(14);state.score=Math.max(0,state.score-10);state.combo=1;showToast("Lane overflow. Incident pressure increased.","bad");checkFailure();return}state.stacks[lane].push(id);el.remove();state.current=null;renderStacks();if(state.stacks[lane].length===3)evaluateLane(lane)}
function renderStacks(){document.querySelectorAll(".stack-card,.clutter").forEach(e=>e.remove());const zoneW=fallZone.clientWidth,colW=zoneW/3,cardW=colW-12;for(let lane=0;lane<3;lane++){let offset=0;for(let c=0;c<state.clutter[lane];c++){const el=document.createElement("div");el.className="clutter";el.style.width=cardW+"px";el.style.left=lane*colW+6+"px";el.style.bottom=10+offset*80+"px";el.innerHTML='<span>⚠ Weak theory<small>Use Flush to remove</small></span>';fallZone.appendChild(el);offset++}state.stacks[lane].forEach(id=>{const clue=CLUES[id],el=document.createElement("div");el.className="stack-card"+(clue.kind==="decoy"?" decoy":"");el.style.width=cardW+"px";el.style.left=lane*colW+6+"px";el.style.bottom=10+offset*80+"px";el.innerHTML=`<span><span class="ico">${clue.icon}</span>${clue.label}</span>`;fallZone.appendChild(el);offset++})}}
function evaluateLane(lane){const ids=[...state.stacks[lane]].sort(),target=[...currentConfig().combo].sort(),correct=ids.join("|")===target.join("|");if(correct){const key=currentStage();state.insights.add(key);state.score+=100*state.combo;state.combo=Math.min(5,state.combo+1);changeLag(-18);state.time+=6;state.stacks[lane]=[];flashLane(lane,true);showToast(`${capitalize(key)} discovered. +6 seconds and pressure reduced.`,"good");confetti(32);updateInsight(key);setTimeout(advanceStage,700)}else{state.stacks[lane]=[];state.clutter[lane]=Math.min(2,state.clutter[lane]+1);state.score=Math.max(0,state.score-15);state.combo=1;changeLag(12);flashLane(lane,false);showToast("Weak theory created clutter. The clues do not form one causal chain.","bad");renderStacks();checkFailure()}updateUI()}
function flashLane(lane,good){fallZone.querySelectorAll(".lane-guide")[lane].animate([{background:"transparent"},{background:good?"rgba(114,229,168,.28)":"rgba(255,133,140,.28)"},{background:"transparent"}],{duration:650})}
function advanceStage(){if(state.stageIndex<2){state.stageIndex++;state.stacks=[[],[],[]];state.clutter=[0,0,0];buildDeck();renderStacks();updateUI();showToast(`${currentConfig().title} is now active.`,"")}else{state.running=false;cancelAnimationFrame(state.animationId);clearInterval(state.timerId);document.getElementById("rushModal").classList.add("show")}}
function move(d){if(state.running&&!state.paused&&state.current){state.lane=Math.max(0,Math.min(2,state.lane+d));positionCurrent()}}function dropNow(){if(state.running&&!state.paused&&state.current){state.fallY=landingY(state.lane);positionCurrent();landCurrent()}}
function changeLag(d){state.lag=Math.max(0,Math.min(100,state.lag+d));updateUI()}function checkFailure(){if(state.lag>=100)finish(false,"Incident pressure hit 100%. Weak theories clogged the investigation.")}
function startTimer(){clearInterval(state.timerId);state.timerId=setInterval(()=>{if(!state.running||state.paused||performance.now()<state.freezeUntil)return;state.time--;if(state.time<=0){state.time=0;updateUI();finish(false,"Time ran out before the root cause was assembled.")}else updateUI()},1000)}
function finish(success,reason){state.running=false;cancelAnimationFrame(state.animationId);clearInterval(state.timerId);const stars=success?(state.lag<45&&state.time>15?3:2):1;document.getElementById("stars").textContent="⭐".repeat(stars)+"☆".repeat(3-stars);document.getElementById("resultTitle").textContent=success?"Incident contained":"Incident escalated";document.getElementById("resultText").textContent=success?`Correct: push raised traffic about 9×, but every activity message used the FIFO group "global", so effective concurrency stayed at one and backlog grew continuously. Final score: ${state.score}.`:`${reason} You uncovered ${state.insights.size}/3 insights. Final score: ${state.score}.`;document.getElementById("resultModal").classList.add("show")}
function updateInsight(key){const el=document.getElementById("i-"+key);el.classList.add("done");el.querySelector("span").textContent=STAGES[key].insight}
function updateUI(){timeEl.textContent=state.time;scoreEl.textContent=state.score;comboEl.textContent="x"+state.combo;lagFill.style.width=state.lag+"%";lagLabel.textContent=state.lag+"%";document.getElementById("timeCard").classList.toggle("danger",state.time<=15);const cfg=currentConfig();document.getElementById("objectiveTitle").textContent=cfg.title;document.getElementById("objectiveText").textContent=cfg.text;stageOrder.forEach((key,index)=>{const p=document.getElementById("p-"+key);p.className="";if(state.insights.has(key))p.classList.add("done");else if(index===state.stageIndex)p.classList.add("current")});document.getElementById("freezeCount").textContent=state.powers.freeze;document.getElementById("flushCount").textContent=state.powers.flush;document.getElementById("inspectCount").textContent=state.powers.inspect;document.getElementById("freezeBtn").disabled=state.powers.freeze<=0;document.getElementById("flushBtn").disabled=state.powers.flush<=0;document.getElementById("inspectBtn").disabled=state.powers.inspect<=0}
function showToast(msg,type){toast.textContent=msg;toast.className="toast show "+(type||"");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.className="toast",2600)}function capitalize(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function confetti(count){const colors=["#ff6fb7","#ffd667","#72e6a8","#70c7ff","#a56bff"];for(let i=0;i<count;i++){const c=document.createElement("div");c.className="confetti";c.style.left=window.innerWidth/2+"px";c.style.top=window.innerHeight/2+"px";c.style.background=colors[i%colors.length];c.style.setProperty("--dx",Math.random()*340-170+"px");c.style.setProperty("--dy",Math.random()*380-60+"px");document.body.appendChild(c);setTimeout(()=>c.remove(),1100)}}
document.getElementById("leftBtn").onclick=()=>move(-1);document.getElementById("rightBtn").onclick=()=>move(1);document.getElementById("dropBtn").onclick=dropNow;
document.getElementById("freezeBtn").onclick=()=>{if(state.powers.freeze<=0||!state.running)return;state.powers.freeze--;state.freezeUntil=performance.now()+5000;showToast("Time frozen for 5 seconds.","good");updateUI()};
document.getElementById("flushBtn").onclick=()=>{if(state.powers.flush<=0||!state.running)return;let lane=state.lane;if(state.clutter[lane]===0)lane=state.clutter.findIndex(v=>v>0);if(lane<0){showToast("No clutter to flush.","");return}state.powers.flush--;state.clutter[lane]=Math.max(0,state.clutter[lane]-1);renderStacks();showToast("One weak theory was removed.","good");updateUI()};
document.getElementById("inspectBtn").onclick=()=>{if(state.powers.inspect<=0||!state.running||!state.current)return;state.powers.inspect--;showToast(CLUES[state.current.id].detail,"");updateUI()};
document.getElementById("helpBtn").onclick=()=>{state.paused=true;document.getElementById("helpModal").classList.add("show")};
document.getElementById("startBtn").onclick=()=>{document.getElementById("helpModal").classList.remove("show");if(!state.running){state.running=true;state.paused=false;buildDeck();spawnClue();startTimer();state.animationId=requestAnimationFrame(gameLoop)}else state.paused=false};
document.querySelectorAll(".choice-row").forEach(row=>{row.addEventListener("click",e=>{const btn=e.target.closest(".choice");if(!btn)return;row.querySelectorAll(".choice").forEach(c=>c.classList.remove("selected"));btn.classList.add("selected");state.selectedRush[row.dataset.group]=btn.textContent.trim()})});
document.getElementById("submitRush").onclick=()=>{const s=state.selectedRush;if(!s.trigger||!s.bottleneck||!s.mechanism){showToast("Choose one statement for each part of the hypothesis.","bad");return}const correct=s.trigger==="Push traffic increased 9×"&&s.bottleneck==="Effective concurrency stayed at one"&&s.mechanism==='Every message used FIFO group "global"';document.getElementById("rushModal").classList.remove("show");if(correct){state.score+=200;finish(true,"");confetti(70)}else finish(false,"The final hypothesis connected the wrong causal chain.")};
document.getElementById("retryBtn").onclick=()=>{document.getElementById("resultModal").classList.remove("show");document.getElementById("rushModal").classList.remove("show");resetGame();document.getElementById("helpModal").classList.add("show")};
let touchStartX=null;fallZone.addEventListener("touchstart",e=>{touchStartX=e.touches[0].clientX},{passive:true});fallZone.addEventListener("touchend",e=>{if(touchStartX===null)return;const dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>35)move(dx>0?1:-1);else dropNow();touchStartX=null},{passive:true});window.addEventListener("resize",()=>{positionCurrent();renderStacks()});resetGame();document.getElementById("helpModal").classList.add("show");